export interface movieDetail {
    // actor: object,
    // caption: string,
    // country: string,
    // detailImg: string,
    // director: string,
    // doubanLink: string,
    // doubanScore: string,
    // downUrl: object,
    // editor: string,
    // fileSize: string,
    // filmLength: string,
    filmType: string,
    // format: string,
    // fullName: string,
    // getAward: string,
    // id: number
    // imdbLink: string,
    // imdbScore: string,
    // indexImgSrc: string,
    // label: string,
    // language: string,
    // onDate: string,
    // pubDate:  string,
    // pureName: string,
    // shortIntro: string,
    // subPureName: string,
    // transName: string,
    // typeId: number,
    // typeName: string,
    // types: string,
    // videoSize: string
    // year: string
}